name: ci-wf
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome steps
        run: echo "Allah Alway Help Me"
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Install Linting Tools
        run: |
          npm install --save-dev htmlhint 
          npm install --save-dev stylelint
      - name: Lint HTML & CSS Files
        run: |
          npx htmlhint "**/*.html" 
          npx stylelint "**/*.css" 